### ISSUE TITLE
Using WEBLATE_ENABLE_HTTPS=1, redirection problems

### ISSUE THREAD

**Issue by Insoleet** [WeblateOrg/docker#118]
Hello,

I'm trying to have weblate working with `WEBLATE_ENABLE_HTTPS=0` to be able to use OAUTH correctly.

My apache2 config is the following : 
```
<VirtualHost *:443>
        ServerName weblate.co.tools
        ServerAdmin webmaster@make.social

        ProxyPass / http://localhost:10080/
        ProxyPassReverse / http://localhost:10080/
        ProxyRequests Off
        ProxyPreserveHost Off

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

SSLCertificateFile /etc/letsencrypt/live/weblate.co.tools/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/weblate.co.tools/privkey.pem
</VirtualHost>
```

The problem I have is that Weblate redirects me to `https://localhost:10080`. If I set `ProxyPassReverse / https://localhost:10080`, I get redirected in loops : 

![image](https://user-images.githubusercontent.com/1170293/52010456-d4e62f80-24d5-11e9-928e-50eb5236213f.png)

My sites seems correctly configured : 

![image](https://user-images.githubusercontent.com/1170293/52010535-0fe86300-24d6-11e9-975b-e38ebb984084.png)

Any idea about what is happening ? My configuration seems kind of standard...

**Comment by nijel** [comment]
If you are not using Docker, then the setting is named without WEBLATE prefix - [ENABLE_HTTPS](https://docs.weblate.org/en/latest/admin/config.html#enable-https).

**Comment by Insoleet** [comment]
I am using docker (Sorry, I forgot to precise it).

**Comment by nijel** [comment]
If you want to have https, you should set `WEBLATE_ENABLE_HTTPS=1` (propably typo in initial comment).

Anyway I think it's misconfigured Apache (though my Apache knowledge is very limited, I used it very long time ago, now I run just nginx):

- The `ProxyPassReverse` rewrites the URLs exactly to what you see, so that one is most likely causing this error, there should be no need for this if Weblate is configured for correct host and gets correct host headers
- Therefore you should enable `ProxyPreserveHost`, so that Weblate sees correct host in the requests.

**Comment by Insoleet** [comment]
Ok, I found what was missing in my configuration. I needed to set `RequestHeader set X-Forwarded-Proto "https"`.

Thanks for your help and pointing my to Apache configuration !

**Comment by alexislg2** [comment]
wow, thanks!
