### ISSUE TITLE
weblate auto_translate --mt deepl xxx xxx en doesn't work

### ISSUE THREAD

**Issue by fleurami** [WeblateOrg/docker#150]
Hi,

I tried to activate weblate deepl mt. Everything seems to be working in the web frontend, but mt inside the docker container doesn't work:

weblate auto_translate --mt deepl xxx xxx en 
- no errors
- inside deepl acc you can see, that the request is send (each request is different in size)
- but no translation is insert into frontend

weblate check --deploy 
-- gives a lot of erros for path: /app/data/* is not writable, check your DATA_DIR settings.

Do I something wrong?

**Comment by nijel** [comment]
The permission error is probably coming from executing some things as root user instead of weblate. This really was not properly documented and the container should deal with that better, I've just committed change to adjust permissions on container startup. Anyway this is not related to problem you see.

I see you're translating into English, what is your source language?

**Comment by fleurami** [comment]
Source language is german, but admin is english.

**Comment by nijel** [comment]
Is the source language correctly set in the project settings?
