### ISSUE TITLE
Running multiple replicas / Horizontally scaling

### ISSUE THREAD

**Issue by brennoo** [WeblateOrg/docker#700]
Hi there,

Is it possible to run multiple containers of weblate for high availability ? We did a simple test running 3 replicas with `/app/data` in a shared filesystem (aws efs) but it didn't work as there were some clash between the containers' files

for example racing conditions:
```
WARNING Handled exception: FileExistsError: [Errno 17] File exists: '/data/home'
```

and deleted cache from each other:
```
Deleting 'CACHE/css/output.64e3cdcf808b.css'
Deleting 'CACHE/js/output.82b1954a0afa.js'
```

is there any config that would make it possible to run it without issues using a shared `WEBLATE_DATA_DIR` 

thank you!

**Comment by nijel** [comment]
There is currently no such option.

**Comment by vitorreis** [comment]
+1 for this request

**Comment by nijel** [comment]
Starting point would be https://github.com/WeblateOrg/docker/issues/683

**Comment by kamilgrymuza** [comment]
This would be super useful for HA environments 👍

**Comment by adriandiazgar** [comment]
+1, urgent need of it

**Comment by nijel** [comment]
>  We did a simple test running 3 replicas with /app/data in a shared filesystem (aws efs)

That should pretty much fine in case the shared filesystem supports file locking.

> for example racing conditions:

There might be race conditions when creating some directories, but these should be harmless.

> and deleted cache from each other:

This is annoying, but harmless, in the end you will have the directory full of correct files. This is caused by fix for https://github.com/WeblateOrg/docker/issues/495
