### ISSUE TITLE
Fix /app/data permission on start

### ISSUE THREAD

**Issue by tnextday** [WeblateOrg/docker#80]
On the first run, the `/app/data` directory permission may be wrong, e.g `root:root`

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by https://github.com/WeblateOrg/docker/pull/81.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
